services:
  app:
    image: remigirard.dev:5000/admin/cv_next-app:${STAGE_NAME}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cv-${STAGE_NAME}.rule=Host(`${DEPLOY_URL}`)"
        - "traefik.http.routers.cv-${STAGE_NAME}.entrypoints=websecure"
        - "traefik.http.routers.cv-${STAGE_NAME}.tls.certresolver=wildcardresolver"
        - "traefik.http.services.cv-${STAGE_NAME}.loadbalancer.server.port=3000"
networks:
  traefik-public:
    external: true
